- name: Install Yugabyte Master Server
  hosts: yb_master
  become: true
  roles:
    - node_exporter
    - yb-common
    - yb-master

- name: Install Yugabyte TServer
  hosts: yb_tserver
  become: true
  roles:
    - node_exporter
    - yb-common
    - yb-tserver

- name: Install Prometheus and Grafana
  hosts: monitoring
  become: yes
  roles:
    - prometheus
    - grafana
